1: 
	gcc -o example_1.exe example_1.c -pthread
	./example_1.exe


2:
	gcc -o example_2_broadcast.exe example_2_broadcast.c -pthread
	./example_2_broadcast.exe


3:
	gcc -o 3_producer_consumer.exe 3_producer_consumer.c -pthread
	./3_producer_consumer.exe

homework:
	gcc -o homework.exe homework.c -pthread
	./homework.exe

clean_all:
	rm -v *.exe

