compile_0: 
	gcc -o 0_thread_creation_steps.exe 0_thread_creation_steps.c -pthread

run_0:
	./0_thread_creation_steps.exe


compile_1:
	gcc -o 1hello_world.exe 1hello_world.c -pthread

run_1:
	./1hello_world.exe

clean_all:
	rm -v *.exe

