compile_1: 
	gcc -o 1_joinable_thread.exe 1_joinable_thread.c -pthread

run_1:
	./1_joinable_thread.exe


compile_2:
	gcc -o 2_detached_thread.exe 2_detached_thread.c -pthread

run_2:
	./2_detached_thread.exe


compile_3:
	gcc -o 3_joinable_to_detach.exe 3_joinable_to_detach.c -pthread

run_3:
	./3_joinable_to_detach.exe


compile_homework:
	gcc -o homework.exe homework.c -pthread

run_homework:
	./homework.exe

clean_all:
	rm -v *.exe
