0:
	gcc -o 0_codevault_introduction_example.exe 0_codevault_introduction_example.c -pthread
	./0_codevault_introduction_example.exe


1:
	gcc -o 1_bathroom_example.exe 1_bathroom_example.c -pthread
	./1_bathroom_example.exe


2:
	gcc -o 2_codevault_login_queue_example.exe 2_codevault_login_queue_example.c -pthread
	./2_codevault_login_queue_example.exe


clear_all:
	rm *.exe
