0:
	gcc -o 0_codevault_introduction_example.exe 0_codevault_introduction_example.c -pthread
	./0_codevault_introduction_example.exe


1:
	gcc -o 1_bathroom_example.exe 1_bathroom_example.c -pthread
	./1_bathroom_example.exe


2:
	gcc -o 2_codevault_binary_semaphores_vs_mutexes.exe 2_codevault_binary_semaphores_vs_mutexes.c -pthread
	./2_codevault_binary_semaphores_vs_mutexes.exe


3:
	gcc -o 3_getting_semaphore_value.exe 3_getting_semaphore_value.c -pthread
	./3_getting_semaphore_value.exe


4:
	gcc -o 4_named_semaphores_waiting.exe 4_named_semaphores_waiting.c -pthread
	gcc -o 4_named_semaphores_signaling.exe 4_named_semaphores_signaling.c -pthread
	./4_named_semaphores_waiting.exe & ./4_named_semaphores_signaling.exe


5:
	gcc -o 5_named_semaphores_example_2.exe 5_named_semaphores_example_2.c -pthread -lrt
	./5_named_semaphores_example_2.exe


clear_all:
	rm *.exe
