compile_1: 
	gcc -o example_1.exe example_1.c -pthread

run_1:
	./example_1.exe


compile_2:
	gcc -o example_2_broadcast.exe example_2_broadcast.c -pthread

run_2:
	./example_2_broadcast.exe

clean_all:
	rm -v *.exe

