0:
	gcc -o 0_basic_barrier_example.exe 0_basic_barrier_example.c -pthread
	./0_basic_barrier_example.exe


1:
	gcc -o 1_barriers_practical_example.exe 1_barriers_practical_example.c -pthread
	./1_barriers_practical_example.exe


clear:
	rm *.exe
