#include <stdlib.h>
#include <memory.h>
#include <assert.h>
#include "notif.h"

/*
    Notification chains is an architectual concept used to notify multiple subscribers interested in the particular event
    Party that generates an event is called "Publisher" and parties that are interested in getting notified are called "Subscribers". There is a one publisher and multiple subscribers
    Event can be generated by the PUblisher and is pushed to subscribers. Subscribers register or de-register for the events at will.
*/
// For further explanation check: https://www.oreilly.com/library/view/understanding-linux-network/0596002556/ch04.html

// Notification chains are generally used in the networking of Linux Kernel.

int main(){
    return 0;
}















