0:
	gcc -o 0_mutex_example.exe 0_mutex_example.c -pthread
	./0_mutex_example.exe

1:
	gcc -o 1_mutexes_bank_balance_different_functions.exe 1_mutexes_bank_balance_different_functions.c -pthread
	./1_mutexes_bank_balance_different_functions.exe

2:
	gcc -o 2_mutex_example_bank.exe 2_mutex_example_bank.c -pthread
	./2_mutex_example_bank.exe

clear:
	rm *.exe
	rm customers.txt
