0:
	gcc -o 0_mutex_example.exe 0_mutex_example.c -pthread
	./0_mutex_example.exe

2:
	gcc -o 2_mutex_example_bank.exe 2_mutex_example_bank.c -pthread
	./2_mutex_example_bank.exe

clear:
	rm *.exe
	rm customers.txt
