co_and_r_0:
	gcc -o 0_asynchronous_cancellation.exe 0_asynchronous_cancellation.c -pthread
	./0_asynchronous_cancellation.exe


co_and_r_1:
	gcc -o 1_terminating_thread.exe 1_terminating_thread.c -pthread
	./1_terminating_thread.exe


clean_all:
	rm *.exe
