0:
	gcc -o 0_asynchronous_cancellation.exe 0_asynchronous_cancellation.c -pthread
	./0_asynchronous_cancellation.exe


1:
	gcc -o 1_terminating_thread.exe 1_terminating_thread.c -pthread
	./1_terminating_thread.exe


2:
	gcc -o 2_asynchronous_cancellation_problems.exe 2_asynchronous_cancellation_problems.c -pthread
	./2_asynchronous_cancellation_problems.exe


3:
	gcc -o 3_asynchronous_cancellation_cleanup.exe 3_asynchronous_cancellation_cleanup.c -pthread
	./3_asynchronous_cancellation_cleanup.exe


clean_all:
	rm *.exe
