0:
	gcc -o 0_recursive_class_example.exe 0_recursive_class_example.c -pthread
	./0_recursive_class_example.exe


1:
	gcc -o 1_codevault_example.exe 1_codevault_example.c -pthread
	./1_codevault_example.exe


clear_all:
	rm *.exe
